### PR TITLE
Upgraded log4net to v2.0.8

### PR DESCRIPTION
**Pull request by robsonj**

### CODE REVIEW

**Comment by robsonj** [comment]
Could you please let me know once you have released a new nuget package with the log4net 2.0.8 dependency?

Cheers
Jonathan

**Comment by jjchiw** [comment]
Hi! I'll merge the PR today at 21:00'ish GMT +1 , and let you know by this thread..... :)

**Comment by jjchiw** [comment]
I pushed the packages :) not at  21:00'ish GMT +1 (yestedary)..... but are pushed now :)

**Comment by robsonj** [comment]
Thank you very much!!

**Pull request merged**
